// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts,js_import_style=legacy_commonjs"
// @generated from file redpanda/api/ui/v1alpha1/network_peering.proto (package redpanda.api.ui.v1alpha1, syntax proto3)
/* eslint-disable */

import { NetworkPeeringService } from "./network_peering_pb";

/**
 * @generated from rpc redpanda.api.ui.v1alpha1.NetworkPeeringService.GetNetworkPeeringInstructions
 */
export const getNetworkPeeringInstructions = NetworkPeeringService.method.getNetworkPeeringInstructions;
