// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: redpanda/api/aigateway/v1/model_providers.proto

package aigatewayv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelProvidersService_GetModelProvider_FullMethodName     = "/redpanda.api.aigateway.v1.ModelProvidersService/GetModelProvider"
	ModelProvidersService_ListModelProviders_FullMethodName   = "/redpanda.api.aigateway.v1.ModelProvidersService/ListModelProviders"
	ModelProvidersService_UpdateModelProvider_FullMethodName  = "/redpanda.api.aigateway.v1.ModelProvidersService/UpdateModelProvider"
	ModelProvidersService_EnableModelProvider_FullMethodName  = "/redpanda.api.aigateway.v1.ModelProvidersService/EnableModelProvider"
	ModelProvidersService_DisableModelProvider_FullMethodName = "/redpanda.api.aigateway.v1.ModelProvidersService/DisableModelProvider"
)

// ModelProvidersServiceClient is the client API for ModelProvidersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModelProvidersService manages LLM provider configurations.
// Providers are seeded by migrations; this service allows enabling/disabling
// and updating provider metadata. Disabling a provider will cascade-disable
// all its models.
type ModelProvidersServiceClient interface {
	GetModelProvider(ctx context.Context, in *GetModelProviderRequest, opts ...grpc.CallOption) (*GetModelProviderResponse, error)
	ListModelProviders(ctx context.Context, in *ListModelProvidersRequest, opts ...grpc.CallOption) (*ListModelProvidersResponse, error)
	UpdateModelProvider(ctx context.Context, in *UpdateModelProviderRequest, opts ...grpc.CallOption) (*UpdateModelProviderResponse, error)
	// Enable a provider for routing (does NOT auto-enable its models)
	EnableModelProvider(ctx context.Context, in *EnableModelProviderRequest, opts ...grpc.CallOption) (*EnableModelProviderResponse, error)
	// Disable a provider (cascade-disables ALL its models)
	DisableModelProvider(ctx context.Context, in *DisableModelProviderRequest, opts ...grpc.CallOption) (*DisableModelProviderResponse, error)
}

type modelProvidersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelProvidersServiceClient(cc grpc.ClientConnInterface) ModelProvidersServiceClient {
	return &modelProvidersServiceClient{cc}
}

func (c *modelProvidersServiceClient) GetModelProvider(ctx context.Context, in *GetModelProviderRequest, opts ...grpc.CallOption) (*GetModelProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelProviderResponse)
	err := c.cc.Invoke(ctx, ModelProvidersService_GetModelProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProvidersServiceClient) ListModelProviders(ctx context.Context, in *ListModelProvidersRequest, opts ...grpc.CallOption) (*ListModelProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelProvidersResponse)
	err := c.cc.Invoke(ctx, ModelProvidersService_ListModelProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProvidersServiceClient) UpdateModelProvider(ctx context.Context, in *UpdateModelProviderRequest, opts ...grpc.CallOption) (*UpdateModelProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateModelProviderResponse)
	err := c.cc.Invoke(ctx, ModelProvidersService_UpdateModelProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProvidersServiceClient) EnableModelProvider(ctx context.Context, in *EnableModelProviderRequest, opts ...grpc.CallOption) (*EnableModelProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableModelProviderResponse)
	err := c.cc.Invoke(ctx, ModelProvidersService_EnableModelProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProvidersServiceClient) DisableModelProvider(ctx context.Context, in *DisableModelProviderRequest, opts ...grpc.CallOption) (*DisableModelProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableModelProviderResponse)
	err := c.cc.Invoke(ctx, ModelProvidersService_DisableModelProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelProvidersServiceServer is the server API for ModelProvidersService service.
// All implementations must embed UnimplementedModelProvidersServiceServer
// for forward compatibility.
//
// ModelProvidersService manages LLM provider configurations.
// Providers are seeded by migrations; this service allows enabling/disabling
// and updating provider metadata. Disabling a provider will cascade-disable
// all its models.
type ModelProvidersServiceServer interface {
	GetModelProvider(context.Context, *GetModelProviderRequest) (*GetModelProviderResponse, error)
	ListModelProviders(context.Context, *ListModelProvidersRequest) (*ListModelProvidersResponse, error)
	UpdateModelProvider(context.Context, *UpdateModelProviderRequest) (*UpdateModelProviderResponse, error)
	// Enable a provider for routing (does NOT auto-enable its models)
	EnableModelProvider(context.Context, *EnableModelProviderRequest) (*EnableModelProviderResponse, error)
	// Disable a provider (cascade-disables ALL its models)
	DisableModelProvider(context.Context, *DisableModelProviderRequest) (*DisableModelProviderResponse, error)
	mustEmbedUnimplementedModelProvidersServiceServer()
}

// UnimplementedModelProvidersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelProvidersServiceServer struct{}

func (UnimplementedModelProvidersServiceServer) GetModelProvider(context.Context, *GetModelProviderRequest) (*GetModelProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelProvider not implemented")
}
func (UnimplementedModelProvidersServiceServer) ListModelProviders(context.Context, *ListModelProvidersRequest) (*ListModelProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModelProviders not implemented")
}
func (UnimplementedModelProvidersServiceServer) UpdateModelProvider(context.Context, *UpdateModelProviderRequest) (*UpdateModelProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModelProvider not implemented")
}
func (UnimplementedModelProvidersServiceServer) EnableModelProvider(context.Context, *EnableModelProviderRequest) (*EnableModelProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableModelProvider not implemented")
}
func (UnimplementedModelProvidersServiceServer) DisableModelProvider(context.Context, *DisableModelProviderRequest) (*DisableModelProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableModelProvider not implemented")
}
func (UnimplementedModelProvidersServiceServer) mustEmbedUnimplementedModelProvidersServiceServer() {}
func (UnimplementedModelProvidersServiceServer) testEmbeddedByValue()                               {}

// UnsafeModelProvidersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelProvidersServiceServer will
// result in compilation errors.
type UnsafeModelProvidersServiceServer interface {
	mustEmbedUnimplementedModelProvidersServiceServer()
}

func RegisterModelProvidersServiceServer(s grpc.ServiceRegistrar, srv ModelProvidersServiceServer) {
	// If the following call pancis, it indicates UnimplementedModelProvidersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelProvidersService_ServiceDesc, srv)
}

func _ModelProvidersService_GetModelProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProvidersServiceServer).GetModelProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProvidersService_GetModelProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProvidersServiceServer).GetModelProvider(ctx, req.(*GetModelProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProvidersService_ListModelProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProvidersServiceServer).ListModelProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProvidersService_ListModelProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProvidersServiceServer).ListModelProviders(ctx, req.(*ListModelProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProvidersService_UpdateModelProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProvidersServiceServer).UpdateModelProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProvidersService_UpdateModelProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProvidersServiceServer).UpdateModelProvider(ctx, req.(*UpdateModelProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProvidersService_EnableModelProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableModelProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProvidersServiceServer).EnableModelProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProvidersService_EnableModelProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProvidersServiceServer).EnableModelProvider(ctx, req.(*EnableModelProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProvidersService_DisableModelProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableModelProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProvidersServiceServer).DisableModelProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProvidersService_DisableModelProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProvidersServiceServer).DisableModelProvider(ctx, req.(*DisableModelProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelProvidersService_ServiceDesc is the grpc.ServiceDesc for ModelProvidersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelProvidersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redpanda.api.aigateway.v1.ModelProvidersService",
	HandlerType: (*ModelProvidersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetModelProvider",
			Handler:    _ModelProvidersService_GetModelProvider_Handler,
		},
		{
			MethodName: "ListModelProviders",
			Handler:    _ModelProvidersService_ListModelProviders_Handler,
		},
		{
			MethodName: "UpdateModelProvider",
			Handler:    _ModelProvidersService_UpdateModelProvider_Handler,
		},
		{
			MethodName: "EnableModelProvider",
			Handler:    _ModelProvidersService_EnableModelProvider_Handler,
		},
		{
			MethodName: "DisableModelProvider",
			Handler:    _ModelProvidersService_DisableModelProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redpanda/api/aigateway/v1/model_providers.proto",
}
