// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file redpanda/api/iam/v1/permission.proto (package redpanda.api.iam.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_api_annotations } from "../../../../google/api/annotations_pb";
import { file_protoc_gen_openapiv2_options_annotations } from "../../../../protoc-gen-openapiv2/options/annotations_pb";
import { file_redpanda_api_iam_v1alpha1_options } from "../v1alpha1/options_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file redpanda/api/iam/v1/permission.proto.
 */
export const file_redpanda_api_iam_v1_permission: GenFile = /*@__PURE__*/
  fileDesc("CiRyZWRwYW5kYS9hcGkvaWFtL3YxL3Blcm1pc3Npb24ucHJvdG8SE3JlZHBhbmRhLmFwaS5pYW0udjEicQoKUGVybWlzc2lvbhIMCgRuYW1lGAEgASgJElUKC2Rlc2NyaXB0aW9uGAIgASgJQkCSQT0yO0EgaHVtYW4tcmVhZGFibGUgZGVzY3JpcHRpb24gb2Ygd2hhdCB0aGUgcGVybWlzc2lvbiBncmFudHMuIhgKFkxpc3RQZXJtaXNzaW9uc1JlcXVlc3QirQEKF0xpc3RQZXJtaXNzaW9uc1Jlc3BvbnNlEpEBCgtwZXJtaXNzaW9ucxgBIAMoCzIfLnJlZHBhbmRhLmFwaS5pYW0udjEuUGVybWlzc2lvbkJbkkFYMh1MaXN0IG9mIGF2YWlsYWJsZSBwZXJtaXNzaW9uc0o3WyJpYW1fcm9sZV9jcmVhdGUiLCAiaWFtX3JvbGVfcmVhZCIsICJpYW1fcm9sZV91cGRhdGUiXTK0BAoRUGVybWlzc2lvblNlcnZpY2USyAMKD0xpc3RQZXJtaXNzaW9ucxIrLnJlZHBhbmRhLmFwaS5pYW0udjEuTGlzdFBlcm1pc3Npb25zUmVxdWVzdBosLnJlZHBhbmRhLmFwaS5pYW0udjEuTGlzdFBlcm1pc3Npb25zUmVzcG9uc2Ui2QKSQYwCEhBMaXN0IHBlcm1pc3Npb25zGi5MaXN0IGFsbCBhdmFpbGFibGUgUmVkcGFuZGEgQ2xvdWQgcGVybWlzc2lvbnMuSj0KAzIwMBI2CgJPSxIwCi4aLC5yZWRwYW5kYS5hcGkuaWFtLnYxLkxpc3RQZXJtaXNzaW9uc1Jlc3BvbnNlSogBCgM1MDASgAEKLEludGVybmFsIFNlcnZlciBFcnJvci4gUmVhY2ggb3V0IHRvIHN1cHBvcnQuEhYKFBoSLmdvb2dsZS5ycGMuU3RhdHVzIjgKB2RlZmF1bHQSLXsiY29kZSI6MTMsIm1lc3NhZ2UiOiJJbnRlcm5hbCBTZXJ2ZXIgRXJyb3Iifcq/By4KDG9yZ2FuaXphdGlvbhIYaWRlbnRpdHkub3JnYW5pemF0aW9uX2lkGgRyZWFkgtPkkwIREg8vdjEvcGVybWlzc2lvbnMaVJJBUQoZQ29udHJvbCBQbGFuZSBQZXJtaXNzaW9ucxI0TWFuYWdlIHlvdXIgUmVkcGFuZGEgQ2xvdWQgb3JnYW5pemF0aW9uIHBlcm1pc3Npb25zLmIGcHJvdG8z", [file_google_api_annotations, file_protoc_gen_openapiv2_options_annotations, file_redpanda_api_iam_v1alpha1_options]);

/**
 * @generated from message redpanda.api.iam.v1.Permission
 */
export type Permission = Message<"redpanda.api.iam.v1.Permission"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;
};

/**
 * Describes the message redpanda.api.iam.v1.Permission.
 * Use `create(PermissionSchema)` to create a new message.
 */
export const PermissionSchema: GenMessage<Permission> = /*@__PURE__*/
  messageDesc(file_redpanda_api_iam_v1_permission, 0);

/**
 * ListPermissionsRequest is the request of ListPermissions.
 *
 * @generated from message redpanda.api.iam.v1.ListPermissionsRequest
 */
export type ListPermissionsRequest = Message<"redpanda.api.iam.v1.ListPermissionsRequest"> & {
};

/**
 * Describes the message redpanda.api.iam.v1.ListPermissionsRequest.
 * Use `create(ListPermissionsRequestSchema)` to create a new message.
 */
export const ListPermissionsRequestSchema: GenMessage<ListPermissionsRequest> = /*@__PURE__*/
  messageDesc(file_redpanda_api_iam_v1_permission, 1);

/**
 * ListPermissionsResponse is the response of ListPermissions.
 *
 * @generated from message redpanda.api.iam.v1.ListPermissionsResponse
 */
export type ListPermissionsResponse = Message<"redpanda.api.iam.v1.ListPermissionsResponse"> & {
  /**
   * @generated from field: repeated redpanda.api.iam.v1.Permission permissions = 1;
   */
  permissions: Permission[];
};

/**
 * Describes the message redpanda.api.iam.v1.ListPermissionsResponse.
 * Use `create(ListPermissionsResponseSchema)` to create a new message.
 */
export const ListPermissionsResponseSchema: GenMessage<ListPermissionsResponse> = /*@__PURE__*/
  messageDesc(file_redpanda_api_iam_v1_permission, 2);

/**
 * PermissionService provides API calls for permission management.
 *
 * @generated from service redpanda.api.iam.v1.PermissionService
 */
export const PermissionService: GenService<{
  /**
   * ListPermissions retrieves all available permissions
   *
   * @generated from rpc redpanda.api.iam.v1.PermissionService.ListPermissions
   */
  listPermissions: {
    methodKind: "unary";
    input: typeof ListPermissionsRequestSchema;
    output: typeof ListPermissionsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_redpanda_api_iam_v1_permission, 0);

