version: 3

vars:
  GO_VERSION: 1.21.6
  BUILD_ROOT: "{{ .ROOT_DIR }}/build"
  GO_BUILD_ROOT: '{{.BUILD_ROOT}}/go/{{.GO_VERSION}}'
  PATH_PREFIX: PATH={{.BUILD_ROOT}}/bin:{{.GO_BUILD_ROOT}}/bin:{{.BUILD_ROOT}}/bin/go:$PATH GOBIN={{ .BUILD_ROOT }}/bin/go GOROOT=
  BACKEND_ROOT: "{{ .ROOT_DIR }}/backend"
  FRONTEND_ROOT: "{{ .ROOT_DIR }}/frontend"
  BRANCH_SLUG:
    sh: git rev-parse --abbrev-ref HEAD | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z

includes:
  backend: taskfiles/backend.yaml
  proto: taskfiles/proto.yaml
