// Code generated by protoc-gen-connect-gateway. DO NOT EDIT.
//
// Source: redpanda/api/aigateway/v1/models.proto

package aigatewayv1connect

import (
	context "context"
	fmt "fmt"

	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	v1 "go.panda.dev/redpanda-aigw/protos/gen/redpanda/api/aigateway/v1"
	connect_gateway "go.vallahaye.net/connect-gateway"
)

// ModelsServiceGatewayServer implements the gRPC server API for the ModelsService service.
type ModelsServiceGatewayServer struct {
	v1.UnimplementedModelsServiceServer
	createModel        connect_gateway.UnaryHandler[v1.CreateModelRequest, v1.CreateModelResponse]
	getModel           connect_gateway.UnaryHandler[v1.GetModelRequest, v1.GetModelResponse]
	listModels         connect_gateway.UnaryHandler[v1.ListModelsRequest, v1.ListModelsResponse]
	updateModel        connect_gateway.UnaryHandler[v1.UpdateModelRequest, v1.UpdateModelResponse]
	deleteModel        connect_gateway.UnaryHandler[v1.DeleteModelRequest, v1.DeleteModelResponse]
	enableModel        connect_gateway.UnaryHandler[v1.EnableModelRequest, v1.EnableModelResponse]
	disableModel       connect_gateway.UnaryHandler[v1.DisableModelRequest, v1.DisableModelResponse]
	listDisabledModels connect_gateway.UnaryHandler[v1.ListDisabledModelsRequest, v1.ListDisabledModelsResponse]
}

// NewModelsServiceGatewayServer constructs a Connect-Gateway gRPC server for the ModelsService
// service.
func NewModelsServiceGatewayServer(svc ModelsServiceHandler, opts ...connect_gateway.HandlerOption) *ModelsServiceGatewayServer {
	return &ModelsServiceGatewayServer{
		createModel:        connect_gateway.NewUnaryHandler(ModelsServiceCreateModelProcedure, svc.CreateModel, opts...),
		getModel:           connect_gateway.NewUnaryHandler(ModelsServiceGetModelProcedure, svc.GetModel, opts...),
		listModels:         connect_gateway.NewUnaryHandler(ModelsServiceListModelsProcedure, svc.ListModels, opts...),
		updateModel:        connect_gateway.NewUnaryHandler(ModelsServiceUpdateModelProcedure, svc.UpdateModel, opts...),
		deleteModel:        connect_gateway.NewUnaryHandler(ModelsServiceDeleteModelProcedure, svc.DeleteModel, opts...),
		enableModel:        connect_gateway.NewUnaryHandler(ModelsServiceEnableModelProcedure, svc.EnableModel, opts...),
		disableModel:       connect_gateway.NewUnaryHandler(ModelsServiceDisableModelProcedure, svc.DisableModel, opts...),
		listDisabledModels: connect_gateway.NewUnaryHandler(ModelsServiceListDisabledModelsProcedure, svc.ListDisabledModels, opts...),
	}
}

func (s *ModelsServiceGatewayServer) CreateModel(ctx context.Context, req *v1.CreateModelRequest) (*v1.CreateModelResponse, error) {
	return s.createModel(ctx, req)
}

func (s *ModelsServiceGatewayServer) GetModel(ctx context.Context, req *v1.GetModelRequest) (*v1.GetModelResponse, error) {
	return s.getModel(ctx, req)
}

func (s *ModelsServiceGatewayServer) ListModels(ctx context.Context, req *v1.ListModelsRequest) (*v1.ListModelsResponse, error) {
	return s.listModels(ctx, req)
}

func (s *ModelsServiceGatewayServer) UpdateModel(ctx context.Context, req *v1.UpdateModelRequest) (*v1.UpdateModelResponse, error) {
	return s.updateModel(ctx, req)
}

func (s *ModelsServiceGatewayServer) DeleteModel(ctx context.Context, req *v1.DeleteModelRequest) (*v1.DeleteModelResponse, error) {
	return s.deleteModel(ctx, req)
}

func (s *ModelsServiceGatewayServer) EnableModel(ctx context.Context, req *v1.EnableModelRequest) (*v1.EnableModelResponse, error) {
	return s.enableModel(ctx, req)
}

func (s *ModelsServiceGatewayServer) DisableModel(ctx context.Context, req *v1.DisableModelRequest) (*v1.DisableModelResponse, error) {
	return s.disableModel(ctx, req)
}

func (s *ModelsServiceGatewayServer) ListDisabledModels(ctx context.Context, req *v1.ListDisabledModelsRequest) (*v1.ListDisabledModelsResponse, error) {
	return s.listDisabledModels(ctx, req)
}

// RegisterModelsServiceHandlerGatewayServer registers the Connect handlers for the ModelsService
// "svc" to "mux".
func RegisterModelsServiceHandlerGatewayServer(mux *runtime.ServeMux, svc ModelsServiceHandler, opts ...connect_gateway.HandlerOption) {
	if err := v1.RegisterModelsServiceHandlerServer(context.TODO(), mux, NewModelsServiceGatewayServer(svc, opts...)); err != nil {
		panic(fmt.Errorf("connect-gateway: %w", err))
	}
}
