/**
 * Copyright 2026 Redpanda Data, Inc.
 *
 * Use of this software is governed by the Business Source License
 * included in the file https://github.com/redpanda-data/redpanda/blob/dev/licenses/bsl.md
 *
 * As of the Change Date specified in that file, in accordance with
 * the Business Source License, use of this software will be governed
 * by the Apache License, Version 2.0
 */

import type { PipelineTemplate } from './pipeline-template-types';

const dsnSlot = (id: string, dbName: string, suggested: string) => ({
  id,
  section: 'source' as const,
  kind: 'secret' as const,
  label: `${dbName} connection DSN`,
  description: `Stored as a Cloud secret. Referenced in YAML as \${secrets.${suggested}}.`,
  suggestedName: suggested,
  required: true,
});

const targetTopicSlot = {
  id: 'targetTopic',
  section: 'sink' as const,
  kind: 'topic' as const,
  label: 'Target Redpanda topic',
  description: 'Records will be written to this topic.',
  required: true,
};

const sourceTopicSlot = {
  id: 'sourceTopic',
  section: 'source' as const,
  kind: 'topic' as const,
  label: 'Source Redpanda topic',
  description: 'Records will be read from this topic.',
  required: true,
};

const consumerGroupSlot = {
  id: 'consumerGroup',
  section: 'options' as const,
  kind: 'string' as const,
  label: 'Consumer group',
  description: 'Identifier used to track read offsets for the source topic.',
  placeholder: 'redpanda-template-consumer',
  required: true,
};

/**
 * v1 curated catalog (PRD §8). The product team owns this list. Adding a template
 * here makes it appear in the gallery. Each entry references components whose names
 * must exist in the backend ComponentList — `useGalleryTemplates()` filters out any
 * template referencing an unknown component.
 */
export const PIPELINE_TEMPLATES: PipelineTemplate[] = [
  // CDC sources to Redpanda
  {
    id: 'postgres-cdc-to-redpanda',
    name: 'Postgres CDC to Redpanda',
    description: 'Stream row-level changes from Postgres into a Redpanda topic via logical replication.',
    category: 'cdc',
    source: { component: 'postgres_cdc', type: 'input' },
    sink: { component: 'redpanda', type: 'output' },
    setupTimeMinutes: 8,
    defaultPipelineName: 'postgres-cdc-pipeline',
    slots: [
      dsnSlot('dsn', 'Postgres', 'POSTGRES_DSN'),
      {
        id: 'includedTables',
        section: 'source',
        kind: 'string',
        label: 'Included tables',
        description: 'Comma-separated list of fully-qualified tables (e.g. public.users,public.orders).',
        placeholder: 'public.users',
        required: true,
      },
      targetTopicSlot,
    ],
  },
  {
    id: 'mysql-cdc-to-redpanda',
    name: 'MySQL CDC to Redpanda',
    description: 'Capture binlog row events from MySQL into a Redpanda topic.',
    category: 'cdc',
    source: { component: 'mysql_cdc', type: 'input' },
    sink: { component: 'redpanda', type: 'output' },
    setupTimeMinutes: 8,
    defaultPipelineName: 'mysql-cdc-pipeline',
    slots: [
      dsnSlot('dsn', 'MySQL', 'MYSQL_DSN'),
      {
        id: 'includedTables',
        section: 'source',
        kind: 'string',
        label: 'Included tables',
        description: 'Comma-separated list of fully-qualified tables (e.g. mydb.users,mydb.orders).',
        placeholder: 'mydb.users',
        required: true,
      },
      targetTopicSlot,
    ],
  },
  {
    id: 'mongodb-cdc-to-redpanda',
    name: 'MongoDB CDC to Redpanda',
    description: 'Stream change-stream events from MongoDB into a Redpanda topic.',
    category: 'cdc',
    source: { component: 'mongodb_cdc', type: 'input' },
    sink: { component: 'redpanda', type: 'output' },
    setupTimeMinutes: 8,
    defaultPipelineName: 'mongodb-cdc-pipeline',
    slots: [
      dsnSlot('url', 'MongoDB', 'MONGODB_URL'),
      {
        id: 'database',
        section: 'source',
        kind: 'string',
        label: 'Database',
        description: 'Source MongoDB database name.',
        required: true,
      },
      {
        id: 'collection',
        section: 'source',
        kind: 'string',
        label: 'Collection',
        description: 'Source MongoDB collection name.',
        required: true,
      },
      targetTopicSlot,
    ],
  },
  {
    id: 'dynamodb-cdc-to-redpanda',
    name: 'DynamoDB CDC to Redpanda',
    description: 'Read DynamoDB Streams records and publish them to a Redpanda topic.',
    category: 'cdc',
    source: { component: 'aws_dynamodb_stream', type: 'input' },
    sink: { component: 'redpanda', type: 'output' },
    setupTimeMinutes: 10,
    defaultPipelineName: 'dynamodb-cdc-pipeline',
    slots: [
      {
        id: 'region',
        section: 'source',
        kind: 'string',
        label: 'AWS region',
        placeholder: 'us-east-1',
        required: true,
      },
      {
        id: 'tableName',
        section: 'source',
        kind: 'string',
        label: 'DynamoDB table',
        required: true,
      },
      dsnSlot('awsAccessKey', 'AWS access key', 'AWS_ACCESS_KEY_ID'),
      dsnSlot('awsSecretKey', 'AWS secret key', 'AWS_SECRET_ACCESS_KEY'),
      targetTopicSlot,
    ],
  },
  {
    id: 'sqlserver-cdc-to-redpanda',
    name: 'SQL Server CDC to Redpanda',
    description: 'Capture CDC-enabled tables from SQL Server into a Redpanda topic.',
    category: 'cdc',
    source: { component: 'sql_server_cdc', type: 'input' },
    sink: { component: 'redpanda', type: 'output' },
    setupTimeMinutes: 10,
    defaultPipelineName: 'sqlserver-cdc-pipeline',
    slots: [
      dsnSlot('dsn', 'SQL Server', 'SQLSERVER_DSN'),
      {
        id: 'includedTables',
        section: 'source',
        kind: 'string',
        label: 'Included tables',
        description: 'Comma-separated list of schema-qualified tables.',
        placeholder: 'dbo.users',
        required: true,
      },
      targetTopicSlot,
    ],
  },
  {
    id: 'oracle-cdc-to-redpanda',
    name: 'Oracle CDC to Redpanda',
    description: 'Capture LogMiner-based row changes from Oracle into a Redpanda topic.',
    category: 'cdc',
    source: { component: 'oracle_cdc', type: 'input' },
    sink: { component: 'redpanda', type: 'output' },
    setupTimeMinutes: 12,
    defaultPipelineName: 'oracle-cdc-pipeline',
    slots: [
      dsnSlot('dsn', 'Oracle', 'ORACLE_DSN'),
      {
        id: 'includedTables',
        section: 'source',
        kind: 'string',
        label: 'Included tables',
        description: 'Comma-separated list of schema-qualified tables.',
        placeholder: 'HR.EMPLOYEES',
        required: true,
      },
      targetTopicSlot,
    ],
  },

  // Ingest sources to Redpanda
  {
    id: 's3-to-redpanda',
    name: 'S3 to Redpanda',
    description: 'Read objects from an Amazon S3 bucket and publish them to a Redpanda topic.',
    category: 'ingest',
    source: { component: 'aws_s3', type: 'input' },
    sink: { component: 'redpanda', type: 'output' },
    setupTimeMinutes: 5,
    defaultPipelineName: 's3-to-redpanda',
    slots: [
      {
        id: 'bucket',
        section: 'source',
        kind: 'string',
        label: 'S3 bucket name',
        required: true,
      },
      {
        id: 'prefix',
        section: 'source',
        kind: 'string',
        label: 'Key prefix',
        description: 'Optional prefix to scope reads. Leave blank for the whole bucket.',
      },
      {
        id: 'region',
        section: 'source',
        kind: 'string',
        label: 'AWS region',
        placeholder: 'us-east-1',
        required: true,
      },
      dsnSlot('awsAccessKey', 'AWS access key', 'AWS_ACCESS_KEY_ID'),
      dsnSlot('awsSecretKey', 'AWS secret key', 'AWS_SECRET_ACCESS_KEY'),
      targetTopicSlot,
    ],
  },
  {
    id: 'http-to-redpanda',
    name: 'HTTP endpoint to Redpanda',
    description: 'Expose an HTTP endpoint that buffers incoming requests onto a Redpanda topic.',
    category: 'ingest',
    source: { component: 'http_server', type: 'input' },
    sink: { component: 'redpanda', type: 'output' },
    setupTimeMinutes: 3,
    defaultPipelineName: 'http-to-redpanda',
    slots: [
      {
        id: 'address',
        section: 'source',
        kind: 'string',
        label: 'Listen address',
        description: 'TCP address the HTTP server should bind to.',
        default: '0.0.0.0:4195',
        required: true,
      },
      {
        id: 'path',
        section: 'source',
        kind: 'string',
        label: 'Request path',
        default: '/post',
        required: true,
      },
      targetTopicSlot,
    ],
  },
  {
    id: 'sqs-to-redpanda',
    name: 'AWS SQS to Redpanda',
    description: 'Drain messages from an Amazon SQS queue into a Redpanda topic.',
    category: 'ingest',
    source: { component: 'aws_sqs', type: 'input' },
    sink: { component: 'redpanda', type: 'output' },
    setupTimeMinutes: 5,
    defaultPipelineName: 'sqs-to-redpanda',
    slots: [
      {
        id: 'queueUrl',
        section: 'source',
        kind: 'string',
        label: 'SQS queue URL',
        placeholder: 'https://sqs.us-east-1.amazonaws.com/123456789012/my-queue',
        required: true,
      },
      {
        id: 'region',
        section: 'source',
        kind: 'string',
        label: 'AWS region',
        placeholder: 'us-east-1',
        required: true,
      },
      dsnSlot('awsAccessKey', 'AWS access key', 'AWS_ACCESS_KEY_ID'),
      dsnSlot('awsSecretKey', 'AWS secret key', 'AWS_SECRET_ACCESS_KEY'),
      targetTopicSlot,
    ],
  },
  {
    id: 'pubsub-to-redpanda',
    name: 'GCP Pub/Sub to Redpanda',
    description: 'Subscribe to a Google Cloud Pub/Sub subscription and publish to Redpanda.',
    category: 'ingest',
    source: { component: 'gcp_pubsub', type: 'input' },
    sink: { component: 'redpanda', type: 'output' },
    setupTimeMinutes: 6,
    defaultPipelineName: 'pubsub-to-redpanda',
    slots: [
      {
        id: 'project',
        section: 'source',
        kind: 'string',
        label: 'GCP project ID',
        required: true,
      },
      {
        id: 'subscription',
        section: 'source',
        kind: 'string',
        label: 'Pub/Sub subscription',
        required: true,
      },
      dsnSlot('credentialsJson', 'GCP service-account JSON', 'GCP_SERVICE_ACCOUNT_JSON'),
      targetTopicSlot,
    ],
  },

  // Redpanda to analytics & lakehouse
  {
    id: 'redpanda-to-snowflake',
    name: 'Redpanda to Snowflake',
    description: 'Stream records from a Redpanda topic into a Snowflake table via Snowpipe Streaming.',
    category: 'analytics',
    source: { component: 'redpanda', type: 'input' },
    sink: { component: 'snowflake_streaming', type: 'output' },
    setupTimeMinutes: 10,
    defaultPipelineName: 'redpanda-to-snowflake',
    slots: [
      sourceTopicSlot,
      consumerGroupSlot,
      {
        id: 'account',
        section: 'sink',
        kind: 'string',
        label: 'Snowflake account',
        placeholder: 'xy12345.us-east-1',
        required: true,
      },
      {
        id: 'user',
        section: 'sink',
        kind: 'string',
        label: 'Snowflake user',
        required: true,
      },
      dsnSlot('privateKey', 'Snowflake RSA private key', 'SNOWFLAKE_PRIVATE_KEY'),
      {
        id: 'database',
        section: 'sink',
        kind: 'string',
        label: 'Database',
        required: true,
      },
      {
        id: 'schema',
        section: 'sink',
        kind: 'string',
        label: 'Schema',
        required: true,
      },
      {
        id: 'table',
        section: 'sink',
        kind: 'string',
        label: 'Table',
        required: true,
      },
    ],
  },
  {
    id: 'redpanda-to-bigquery',
    name: 'Redpanda to BigQuery',
    description: 'Stream records from a Redpanda topic into a BigQuery table.',
    category: 'analytics',
    source: { component: 'redpanda', type: 'input' },
    sink: { component: 'gcp_bigquery', type: 'output' },
    setupTimeMinutes: 10,
    defaultPipelineName: 'redpanda-to-bigquery',
    slots: [
      sourceTopicSlot,
      consumerGroupSlot,
      {
        id: 'project',
        section: 'sink',
        kind: 'string',
        label: 'GCP project ID',
        required: true,
      },
      {
        id: 'dataset',
        section: 'sink',
        kind: 'string',
        label: 'BigQuery dataset',
        required: true,
      },
      {
        id: 'table',
        section: 'sink',
        kind: 'string',
        label: 'BigQuery table',
        required: true,
      },
      dsnSlot('credentialsJson', 'GCP service-account JSON', 'GCP_SERVICE_ACCOUNT_JSON'),
    ],
  },
  {
    id: 'redpanda-to-iceberg',
    name: 'Redpanda to Iceberg',
    description: 'Write records from a Redpanda topic into an Apache Iceberg table.',
    category: 'analytics',
    source: { component: 'redpanda', type: 'input' },
    sink: { component: 'iceberg', type: 'output' },
    setupTimeMinutes: 12,
    defaultPipelineName: 'redpanda-to-iceberg',
    slots: [
      sourceTopicSlot,
      consumerGroupSlot,
      {
        id: 'catalogUri',
        section: 'sink',
        kind: 'string',
        label: 'Iceberg catalog URI',
        placeholder: 'https://glue.us-east-1.amazonaws.com',
        required: true,
      },
      {
        id: 'warehouse',
        section: 'sink',
        kind: 'string',
        label: 'Warehouse location',
        placeholder: 's3://my-bucket/warehouse',
        required: true,
      },
      {
        id: 'namespace',
        section: 'sink',
        kind: 'string',
        label: 'Namespace',
        required: true,
      },
      {
        id: 'tableName',
        section: 'sink',
        kind: 'string',
        label: 'Table name',
        required: true,
      },
    ],
  },
  {
    id: 'redpanda-to-postgres',
    name: 'Redpanda to Postgres',
    description: 'Write records from a Redpanda topic into a Postgres table.',
    category: 'analytics',
    source: { component: 'redpanda', type: 'input' },
    sink: { component: 'sql_raw', type: 'output' },
    setupTimeMinutes: 6,
    defaultPipelineName: 'redpanda-to-postgres',
    slots: [
      sourceTopicSlot,
      consumerGroupSlot,
      dsnSlot('dsn', 'Postgres', 'POSTGRES_DSN'),
      {
        id: 'tableName',
        section: 'sink',
        kind: 'string',
        label: 'Target table',
        required: true,
      },
    ],
  },

  // Migration & replication
  {
    id: 'kafka-to-redpanda-migration',
    name: 'Kafka to Redpanda migration',
    description: 'Replicate topics, schemas, and consumer offsets from a Kafka cluster into Redpanda.',
    category: 'migration',
    source: { component: 'redpanda_migrator', type: 'input' },
    sink: { component: 'redpanda', type: 'output' },
    setupTimeMinutes: 15,
    defaultPipelineName: 'kafka-to-redpanda-migration',
    slots: [
      {
        id: 'sourceBrokers',
        section: 'source',
        kind: 'string',
        label: 'Source Kafka brokers',
        description: 'Comma-separated list of bootstrap brokers.',
        placeholder: 'broker1.example.com:9092,broker2.example.com:9092',
        required: true,
      },
      {
        id: 'sourceTopics',
        section: 'source',
        kind: 'string',
        label: 'Source topic regex',
        description: 'Topics matching this regex will be migrated.',
        placeholder: '.*',
        required: true,
      },
      dsnSlot('sourceUser', 'Source SASL user', 'SOURCE_KAFKA_USER'),
      dsnSlot('sourcePassword', 'Source SASL password', 'SOURCE_KAFKA_PASSWORD'),
    ],
  },
  {
    id: 'redpanda-to-redpanda-mirrored',
    name: 'Redpanda to Redpanda mirrored',
    description: 'Mirror a topic from one Redpanda cluster to another for active-passive replication.',
    category: 'migration',
    source: { component: 'redpanda', type: 'input' },
    sink: { component: 'redpanda_migrator', type: 'output' },
    setupTimeMinutes: 10,
    defaultPipelineName: 'redpanda-mirror',
    slots: [
      sourceTopicSlot,
      consumerGroupSlot,
      {
        id: 'destBrokers',
        section: 'sink',
        kind: 'string',
        label: 'Destination Redpanda brokers',
        description: 'Comma-separated list of bootstrap brokers for the destination cluster.',
        placeholder: 'broker1.example.com:9092',
        required: true,
      },
      {
        id: 'destTopic',
        section: 'sink',
        kind: 'string',
        label: 'Destination topic name',
        required: true,
      },
      dsnSlot('destUser', 'Destination SASL user', 'DEST_KAFKA_USER'),
      dsnSlot('destPassword', 'Destination SASL password', 'DEST_KAFKA_PASSWORD'),
    ],
  },
];

export const getTemplateById = (id: string): PipelineTemplate | undefined =>
  PIPELINE_TEMPLATES.find((t) => t.id === id);
