import {
    PlusIcon,
    SunIcon,
    MoonIcon,
    SearchIcon,
    TrashIcon,
    AdjustmentsIcon,
    InformationCircleIcon,
    CloudDownloadIcon,
    XIcon,
    DocumentDuplicateIcon,
    DocumentTextIcon,
    ArrowSmLeftIcon,
    ArrowSmRightIcon,
    RefreshIcon,
    PencilIcon,
    FolderIcon,
    ChevronDoubleRightIcon,
    ChevronDoubleLeftIcon,
    BadgeCheckIcon,
    ExclamationIcon,
    BellIcon,
    PlayIcon,
    StopIcon,
    ShareIcon,
    MapIcon,
    ExclamationCircleIcon,
    UserIcon,
    UsersIcon,
    BriefcaseIcon,
    LockClosedIcon,
    LockOpenIcon,
    ClipboardListIcon,
    NewspaperIcon,
    PuzzleIcon,
    MailIcon,
    ChevronRightIcon,
    TicketIcon,
} from '@heroicons/react/outline'

const heroIconProps = {
    style: {
        height: '1rem',
        width: '1rem',
        // display: 'inline-block',
        color: 'var(--bstdio-color)',
    },
    className: 'heroIcon',
};

const heroIcons = {
    plus: <PlusIcon style={heroIconProps.style} className={heroIconProps.className} />,
    light: <SunIcon style={heroIconProps.style} className={heroIconProps.className} />,
    dark: <MoonIcon style={heroIconProps.style} className={heroIconProps.className} />,
    search: <SearchIcon style={heroIconProps.style} className={heroIconProps.className} />,
    share: <ShareIcon style={heroIconProps.style} className={heroIconProps.className} />,
    delete: <TrashIcon style={heroIconProps.style} className={heroIconProps.className} />,
    settings: <AdjustmentsIcon style={heroIconProps.style} className={heroIconProps.className} />,
    info: <InformationCircleIcon style={heroIconProps.style} className={heroIconProps.className} />,
    download: <CloudDownloadIcon style={heroIconProps.style} className={heroIconProps.className} />,
    close: <XIcon style={heroIconProps.style} className={heroIconProps.className} />,
    close_black: <XIcon style={
        { ...heroIconProps.style, color: '#000000' }
    } className={heroIconProps.className} />,
    copy: <DocumentDuplicateIcon style={heroIconProps.style} className={heroIconProps.className} />,
    document: <DocumentTextIcon style={heroIconProps.style} className={heroIconProps.className} />,
    back: <ArrowSmLeftIcon style={heroIconProps.style} className={heroIconProps.className} />,
    undo: <ArrowSmLeftIcon style={heroIconProps.style} className={heroIconProps.className} />,
    redo: <ArrowSmRightIcon style={heroIconProps.style} className={heroIconProps.className} />,
    refresh: <RefreshIcon style={heroIconProps.style} className={heroIconProps.className} />,
    refresh_rotating: <RefreshIcon style={
        { ...heroIconProps.style, animation: 'var(--bstdio-loading-rotation)' }
    } className={heroIconProps.className} />,
    edit: <PencilIcon style={heroIconProps.style} className={heroIconProps.className} />,
    folder: <FolderIcon style={heroIconProps.style} className={heroIconProps.className} />,
    expand: <ChevronDoubleRightIcon style={heroIconProps.style} className={heroIconProps.className} />,
    collapse: <ChevronDoubleLeftIcon style={heroIconProps.style} className={heroIconProps.className} />,
    warning: <ExclamationIcon style={heroIconProps.style} className={heroIconProps.className} />,
    warning_yellow: <ExclamationIcon style={
        { ...heroIconProps.style, color: 'var(--bstdio-yellow)' }
    } className={heroIconProps.className} />,
    warning_red: <ExclamationIcon style={
        { ...heroIconProps.style, color: 'var(--bstdio-pink)' }
    } className={heroIconProps.className} />,
    warning_white: <ExclamationIcon style={
        { ...heroIconProps.style, color: 'white' }
    } className={heroIconProps.className} />,
    alert: <BellIcon style={heroIconProps.style} className={heroIconProps.className} />,
    run: <PlayIcon style={heroIconProps.style} className={heroIconProps.className} />,
    stop: <StopIcon style={heroIconProps.style} className={heroIconProps.className} />,
    run_white: <PlayIcon style={
        { ...heroIconProps.style, color: 'var(--bstdio-white)' }
    } className={heroIconProps.className} />,
    graph: <MapIcon style={heroIconProps.style} className={heroIconProps.className} />,
    exclamation: <ExclamationCircleIcon style={heroIconProps.style} className={heroIconProps.className} />,
    exclamation_white: <ExclamationCircleIcon style={
        { ...heroIconProps.style, color: 'var(--bstdio-white)' }
    } className={heroIconProps.className} />,
    user: <UserIcon style={heroIconProps.style} className={heroIconProps.className} />,
    users: <UsersIcon style={heroIconProps.style} className={heroIconProps.className} />,
    toolbox: <BriefcaseIcon style={heroIconProps.style} className={heroIconProps.className} />,
    locked: <LockClosedIcon style={heroIconProps.style} className={heroIconProps.className} />,
    unlocked: <LockOpenIcon style={heroIconProps.style} className={heroIconProps.className} />,
    list: <ClipboardListIcon style={heroIconProps.style} className={heroIconProps.className} />,
    news: <NewspaperIcon style={heroIconProps.style} className={heroIconProps.className} />,
    schema: <PuzzleIcon style={heroIconProps.style} className={heroIconProps.className} />,
    mail: <MailIcon style={heroIconProps.style} className={heroIconProps.className} />,
    chevronright: <ChevronRightIcon style={heroIconProps.style} className={heroIconProps.className} />,
    ticket: <TicketIcon style={heroIconProps.style} className={heroIconProps.className} />,
    check_badge: <BadgeCheckIcon style={heroIconProps.style} className={heroIconProps.className} />,
};
export default heroIcons;

export const emoji = {
    //   light: '🌞',
    //   dark: '🌚',
    //   search: '🔍',
    //   delete: '🗑',
    //   settings: '⚙️',
    //   info: 'ℹ️',
    download: '📥',
    //   close: '✖',
    //   document: '📄',
    //   back: '↩️',
    //   undo: '↩️',
    //   redo: '↪️️',
    //   refresh: '🔄',
    //   edit: '✏️',
    //   folder: '📁',
    //   collapse: '⏪',
    //   warning: '⚠️',
    //   alert: '🔔',
    //   run: '▶️',
    //   graph: '🌐',
    //   exclamation: '❗',
    //   user: '👤',
    //   users: '👥',
    //   toolbox: '🧰',
    locked: '🔒',
    unlocked: '🔓',
    ghost: '👻',
    //   list: '📜',
    //   news: '📰',
    //   schema: '🧭',
};
