import {
  SiApachekafka,
  SiApacheparquet,
  SiApachepulsar,
  SiClickhouse,
  SiCockroachlabs,
  SiDgraph,
  SiJaeger,
  SiMqtt,
  SiNeo4j,
  SiOllama,
  SiOpenai,
  SiSalesforce,
  SiSplunk,
  SiTrino,
} from '@icons-pack/react-simple-icons';
import { RedpandaUILetterIcon } from 'components/redpanda-ui/components/icons';
import {
  Activity,
  Archive,
  ArrowRightLeft,
  Ban,
  BarChart3,
  Bomb,
  BookOpen,
  Boxes,
  Braces,
  CircleSlash,
  Columns3,
  Command,
  Cpu,
  Database,
  Eraser,
  File,
  FileArchive,
  FileInput,
  FileJson,
  FileOutput,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Filter,
  Folder,
  FolderOpen,
  FolderUp,
  GitBranch,
  GitFork,
  Globe,
  HardDrive,
  Layers,
  LifeBuoy,
  ListOrdered,
  MemoryStick,
  Moon,
  MousePointer,
  Network,
  Package,
  PlusSquare,
  Radio,
  RefreshCw,
  Regex,
  Repeat,
  Replace,
  Reply,
  Ruler,
  Scissors,
  ScrollText,
  Server,
  Settings,
  Share2,
  Shield,
  Sparkles,
  Terminal,
  Type,
  Wand2,
  Workflow,
  Zap,
} from 'lucide-react';
import type { SVGProps } from 'react';

import {
  AmazonWebServicesLogo,
  ApacheactivemqLogo,
  ApacheavroLogo,
  AuthzedLogo,
  AWSCloudWatchLogo,
  AWSDynamoDbLogo,
  AWSKinesisLogo,
  AWSLambdaLogo,
  AWSS3Logo,
  AWSSNSLogo,
  AWSSQSLogo,
  BeanstalkdLogo,
  CassandraLogo,
  CohereLogo,
  CouchbaseLogo,
  DiscordLogo,
  ElasticsearchLogo,
  GnuLogo,
  GoogleCloudLogo,
  GoogleDriveLogo,
  GoogleProtocolBuffersLogo,
  HadoopLogo,
  IcebergLogo,
  InfluxDBLogo,
  JavaScriptLogo,
  JqLogo,
  JSONLogo,
  MemcachedLogo,
  MicrosoftazureLogo,
  MicrosoftsqlserverLogo,
  MongoDBLogo,
  MySQLLogo,
  NanomsgLogo,
  NatsLogo,
  NsqLogo,
  OpenSearchLogo,
  OpenTelemetryLogo,
  OracleLogo,
  PineconeLogo,
  PostgreSQLLogo,
  PrometheusLogo,
  PusherLogo,
  QdrantLogo,
  RabbitMQLogo,
  RedisLogo,
  SentryLogo,
  SlackLogo,
  SnowflakeLogo,
  WebSocketLogo,
  XmlLogo,
} from './logos';

const RedpandaLetterLogo = (props: SVGProps<SVGSVGElement>) => (
  <RedpandaUILetterIcon {...props} style={{ color: '#E14226', ...props.style }} />
);

export const componentLogoMap = {
  custom: Settings,
  amqp_0_9: RabbitMQLogo,
  amqp_1: ApacheactivemqLogo,
  arc: BarChart3,
  archive: Archive,
  avro: ApacheavroLogo,
  awk: GnuLogo,
  aws_bedrock_chat: AmazonWebServicesLogo,
  aws_bedrock_embeddings: AmazonWebServicesLogo,
  aws_cloudwatch: AWSCloudWatchLogo,
  aws_cloudwatch_logs: AWSCloudWatchLogo,
  aws_dynamodb: AWSDynamoDbLogo,
  aws_dynamodb_cdc: AWSDynamoDbLogo,
  aws_dynamodb_partiql: AWSDynamoDbLogo,
  aws_kinesis: AWSKinesisLogo,
  aws_kinesis_firehose: AWSKinesisLogo,
  aws_lambda: AWSLambdaLogo,
  aws_s3: AWSS3Logo,
  aws_sns: AWSSNSLogo,
  aws_sqs: AWSSQSLogo,
  azure_blob_storage: MicrosoftazureLogo,
  azure_cosmosdb: MicrosoftazureLogo,
  azure_data_lake_gen2: MicrosoftazureLogo,
  azure_queue_storage: MicrosoftazureLogo,
  azure_table_storage: MicrosoftazureLogo,
  batched: Package,
  beanstalkd: BeanstalkdLogo,
  benchmark: Activity,
  bloblang: RedpandaLetterLogo,
  bounds_check: Ruler,
  branch: GitFork,
  broker: Share2,
  cache: Database,
  cached: Database,
  cassandra: CassandraLogo,
  catch: Shield,
  chunker: Scissors,
  cockroachdb_changefeed: SiCockroachlabs,
  cohere_chat: CohereLogo,
  cohere_embeddings: CohereLogo,
  cohere_rerank: CohereLogo,
  command: Command,
  compress: FileArchive,
  couchbase: CouchbaseLogo,
  crash: Bomb,
  csv: FileSpreadsheet,
  cyborgdb: Database,
  cypher: SiNeo4j,
  decompress: FolderOpen,
  dedupe: Filter,
  discord: DiscordLogo,
  drop: Ban,
  drop_on: Ban,
  dynamic: Zap,
  elasticsearch_v8: ElasticsearchLogo,
  fallback: LifeBuoy,
  file: File,
  for_each: Repeat,
  gateway: Network,
  gcp_bigquery: GoogleCloudLogo,
  gcp_bigquery_select: GoogleCloudLogo,
  gcp_cloud_storage: GoogleCloudLogo,
  gcp_cloudtrace: GoogleCloudLogo,
  gcp_pubsub: GoogleCloudLogo,
  gcp_spanner_cdc: GoogleCloudLogo,
  gcp_vertex_ai_chat: GoogleCloudLogo,
  gcp_vertex_ai_embeddings: GoogleCloudLogo,
  generate: Sparkles,
  git: GitBranch,
  google_drive_download: GoogleDriveLogo,
  google_drive_list_labels: GoogleDriveLogo,
  google_drive_search: GoogleDriveLogo,
  grok: ElasticsearchLogo,
  group_by: Layers,
  group_by_value: Layers,
  hdfs: HadoopLogo,
  http: Globe,
  http_client: Globe,
  http_server: Server,
  iceberg: IcebergLogo,
  influxdb: InfluxDBLogo,
  inproc: Cpu,
  insert_part: PlusSquare,
  jaeger: SiJaeger,
  javascript: JavaScriptLogo,
  jmespath: Braces,
  jq: JqLogo,
  json_api: JSONLogo,
  json_array: JSONLogo,
  json_documents: JSONLogo,
  json_schema: JSONLogo,
  kafka: SiApachekafka,
  kafka_franz: SiApachekafka,
  lines: FileText,
  local: Folder,
  log: ScrollText,
  logger: ScrollText,
  lru: HardDrive,
  mapping: ArrowRightLeft,
  memcached: MemcachedLogo,
  memory: MemoryStick,
  metric: BarChart3,
  microsoft_sql_server_cdc: MicrosoftsqlserverLogo,
  mongodb: MongoDBLogo,
  mongodb_cdc: MongoDBLogo,
  mqtt: SiMqtt,
  msgpack: Package,
  multilevel: Boxes,
  mutation: Wand2,
  mysql_cdc: MySQLLogo,
  nanomsg: NanomsgLogo,
  nats: NatsLogo,
  nats_jetstream: NatsLogo,
  nats_kv: NatsLogo,
  nats_request_reply: NatsLogo,
  nats_stream: NatsLogo,
  none: undefined,
  noop: CircleSlash,
  nsq: NsqLogo,
  ockam_kafka: SiApachekafka,
  ollama_chat: SiOllama,
  ollama_embeddings: SiOllama,
  ollama_moderation: SiOllama,
  open_telemetry_collector: OpenTelemetryLogo,
  openai_chat_completion: SiOpenai,
  openai_embeddings: SiOpenai,
  openai_image_generation: SiOpenai,
  openai_speech: SiOpenai,
  openai_transcription: SiOpenai,
  openai_translation: SiOpenai,
  opensearch: OpenSearchLogo,
  oracledb_cdc: OracleLogo,
  otlp_grpc: OpenTelemetryLogo,
  otlp_http: OpenTelemetryLogo,
  parallel: Columns3,
  parquet: SiApacheparquet,
  parquet_decode: SiApacheparquet,
  parquet_encode: SiApacheparquet,
  parse_log: FileSearch,
  pg_stream: PostgreSQLLogo,
  pinecone: PineconeLogo,
  postgres: PostgreSQLLogo,
  postgres_cdc: PostgreSQLLogo,
  processors: Cpu,
  prometheus: PrometheusLogo,
  protobuf: GoogleProtocolBuffersLogo,
  pulsar: SiApachepulsar,
  pusher: PusherLogo,
  qdrant: QdrantLogo,
  questdb: Database,
  rate_limit: Activity,
  re_match: Regex,
  read_until: BookOpen,
  redis: RedisLogo,
  redis_hash: RedisLogo,
  redis_list: RedisLogo,
  redis_pubsub: RedisLogo,
  redis_scan: RedisLogo,
  redis_script: RedisLogo,
  redis_streams: RedisLogo,
  redpanda: RedpandaLetterLogo,
  redpanda_common: RedpandaLetterLogo,
  redpanda_data_transform: RedpandaLetterLogo,
  redpanda_migrator: RedpandaLetterLogo,
  redpanda_migrator_bundle: RedpandaLetterLogo,
  redpanda_migrator_offsets: RedpandaLetterLogo,
  reject: Ban,
  reject_errored: Ban,
  resource: Package,
  retry: RefreshCw,
  ristretto: SiDgraph,
  salesforce: SiSalesforce,
  salesforce_cdc: SiSalesforce,
  salesforce_graphql: SiSalesforce,
  salesforce_sink: SiSalesforce,
  schema_registry: FileJson,
  schema_registry_decode: FileJson,
  schema_registry_encode: FileJson,
  select_parts: MousePointer,
  sentry_capture: SentryLogo,
  sequence: ListOrdered,
  sftp: FolderUp,
  skip_bom: Eraser,
  slack: SlackLogo,
  slack_post: SlackLogo,
  slack_reaction: SlackLogo,
  slack_thread: SlackLogo,
  slack_users: SlackLogo,
  sleep: Moon,
  snowflake_put: SnowflakeLogo,
  snowflake_streaming: SnowflakeLogo,
  socket: Network,
  socket_server: Server,
  spicedb_watch: AuthzedLogo,
  split: Scissors,
  splunk: SiSplunk,
  splunk_hec: SiSplunk,
  sql: Database,
  sql_driver_clickhouse: SiClickhouse,
  sql_driver_gocosmos: MicrosoftazureLogo,
  sql_driver_mssql: MicrosoftsqlserverLogo,
  sql_driver_mysql: MySQLLogo,
  sql_driver_oracle: OracleLogo,
  sql_driver_postgres: PostgreSQLLogo,
  sql_driver_snowflake: SnowflakeLogo,
  sql_driver_sqlite: MySQLLogo,
  sql_driver_trino: SiTrino,
  sql_raw: Database,
  sql_select: Database,
  stdin: FileInput,
  stdout: FileOutput,
  subprocess: Terminal,
  switch: Replace,
  sync_response: Reply,
  tcp: Network,
  tcp_server: Server,
  text: Type,
  timeplus: Database,
  tracer: OpenTelemetryLogo,
  try: Shield,
  unarchive: FolderOpen,
  websocket: WebSocketLogo,
  while: Repeat,
  workflow: Workflow,
  xml: XmlLogo,
  zmq4: Radio,
} as const;

export type ComponentName = keyof typeof componentLogoMap;
