import {
  SiApachecassandra,
  SiApachehadoop,
  SiApachekafka,
  SiApacheparquet,
  SiApachepulsar,
  SiClickhouse,
  SiCockroachlabs,
  SiCouchbase,
  SiDgraph,
  SiDiscord,
  SiElastic,
  SiElasticsearch,
  SiGnu,
  SiGooglebigquery,
  SiGooglecloud,
  SiGoogledrive,
  SiGooglepubsub,
  SiInfluxdb,
  SiJaeger,
  SiJavascript,
  SiJson,
  SiMongodb,
  SiMqtt,
  SiMysql,
  SiNatsdotio,
  SiNeo4j,
  SiOllama,
  SiOpenai,
  SiOpensearch,
  SiOpentelemetry,
  SiPostgresql,
  SiPrometheus,
  SiPusher,
  SiRabbitmq,
  SiRedis,
  SiSentry,
  SiSlack,
  SiSnowflake,
  SiSplunk,
  SiSqlite,
  SiTrino,
} from '@icons-pack/react-simple-icons';
import {
  Activity,
  Archive,
  BarChart3,
  CircleSlash,
  Command,
  Cpu,
  Database,
  File,
  FileArchive,
  FileInput,
  FileOutput,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Folder,
  FolderOpen,
  GitBranch,
  Globe,
  Network,
  Package,
  RefreshCw,
  ScrollText,
  Server,
  Terminal,
  Type,
  Workflow,
} from 'lucide-react';

import {
  AmazondynamodbLogo,
  Amazons3Logo,
  AmazonsqsLogo,
  AmazonWebServicesLogo,
  ApacheactivemqLogo,
  ApacheavroLogo,
  AuthzedLogo,
  AwslambdaLogo,
  AzurecosmosdbLogo,
  BeanstalkdLogo,
  CohereLogo,
  ConfluentincLogo,
  GoogleProtocolBuffersLogo,
  JqLogo,
  MemcachedLogo,
  MicrosoftazureLogo,
  MicrosoftsqlserverLogo,
  MsgpackLogo,
  NanomsgLogo,
  NsqLogo,
  OracleLogo,
  PineconeLogo,
  QdrantLogo,
  QuestdbLogo,
  RedpandaLogo,
  WebSocketLogo,
  XmlLogo,
  ZeromqLogo,
} from './logos';

export const componentLogoMap = {
  amqp_0_9: SiRabbitmq,
  amqp_1: ApacheactivemqLogo,
  archive: Archive,
  avro: ApacheavroLogo,
  awk: SiGnu,
  aws_bedrock_chat: AmazonWebServicesLogo,
  aws_bedrock_embeddings: AmazonWebServicesLogo,
  aws_cloudwatch: AmazonWebServicesLogo,
  aws_dynamodb: AmazondynamodbLogo,
  aws_dynamodb_partiql: AmazondynamodbLogo,
  aws_kinesis: AmazonWebServicesLogo,
  aws_kinesis_firehose: AmazonWebServicesLogo,
  aws_lambda: AwslambdaLogo,
  aws_s3: Amazons3Logo,
  aws_sns: AmazonWebServicesLogo,
  aws_sqs: AmazonsqsLogo,
  azure_blob_storage: MicrosoftazureLogo,
  azure_cosmosdb: AzurecosmosdbLogo,
  azure_data_lake_gen2: MicrosoftazureLogo,
  azure_queue_storage: MicrosoftazureLogo,
  azure_table_storage: MicrosoftazureLogo,
  batched: Package,
  beanstalkd: BeanstalkdLogo,
  benchmark: Activity,
  bloblang: RedpandaLogo,
  bounds_check: undefined,
  branch: undefined,
  broker: undefined,
  cache: Database,
  cached: Database,
  cassandra: SiApachecassandra,
  catch: undefined,
  chunker: undefined,
  cockroachdb_changefeed: SiCockroachlabs,
  cohere_chat: CohereLogo,
  cohere_embeddings: CohereLogo,
  cohere_rerank: CohereLogo,
  command: Command,
  compress: FileArchive,
  couchbase: SiCouchbase,
  crash: undefined,
  csv: FileSpreadsheet,
  cyborgdb: undefined,
  cypher: SiNeo4j,
  decompress: FolderOpen,
  dedupe: undefined,
  discord: SiDiscord,
  drop: undefined,
  drop_on: undefined,
  dynamic: undefined,
  elasticsearch_v8: SiElasticsearch,
  fallback: undefined,
  file: File,
  for_each: undefined,
  gateway: Network,
  gcp_bigquery: SiGooglebigquery,
  gcp_bigquery_select: SiGooglebigquery,
  gcp_cloud_storage: SiGooglecloud,
  gcp_cloudtrace: SiGooglecloud,
  gcp_pubsub: SiGooglepubsub,
  gcp_spanner_cdc: SiGooglecloud,
  gcp_vertex_ai_chat: SiGooglecloud,
  gcp_vertex_ai_embeddings: SiGooglecloud,
  generate: undefined,
  git: GitBranch,
  google_drive_download: SiGoogledrive,
  google_drive_list_labels: SiGoogledrive,
  google_drive_search: SiGoogledrive,
  grok: SiElastic,
  group_by: undefined,
  group_by_value: undefined,
  hdfs: SiApachehadoop,
  http: Globe,
  http_client: Globe,
  http_server: Server,
  influxdb: SiInfluxdb,
  inproc: undefined,
  insert_part: undefined,
  jaeger: SiJaeger,
  javascript: SiJavascript,
  jmespath: undefined,
  jq: JqLogo,
  json_api: SiJson,
  json_array: SiJson,
  json_documents: SiJson,
  json_schema: SiJson,
  kafka: SiApachekafka,
  kafka_franz: SiApachekafka,
  lines: FileText,
  local: Folder,
  log: ScrollText,
  logger: ScrollText,
  lru: undefined,
  mapping: undefined,
  memcached: MemcachedLogo,
  memory: undefined,
  metric: BarChart3,
  microsoft_sql_server_cdc: MicrosoftsqlserverLogo,
  mongodb: SiMongodb,
  mongodb_cdc: SiMongodb,
  mqtt: SiMqtt,
  msgpack: MsgpackLogo,
  multilevel: undefined,
  mutation: undefined,
  mysql_cdc: SiMysql,
  nanomsg: NanomsgLogo,
  nats: SiNatsdotio,
  nats_jetstream: SiNatsdotio,
  nats_kv: SiNatsdotio,
  nats_request_reply: SiNatsdotio,
  nats_stream: SiNatsdotio,
  none: undefined,
  noop: CircleSlash,
  nsq: NsqLogo,
  ockam_kafka: SiApachekafka,
  ollama_chat: SiOllama,
  ollama_embeddings: SiOllama,
  ollama_moderation: SiOllama,
  open_telemetry_collector: SiOpentelemetry,
  openai_chat_completion: SiOpenai,
  openai_embeddings: SiOpenai,
  openai_image_generation: SiOpenai,
  openai_speech: SiOpenai,
  openai_transcription: SiOpenai,
  openai_translation: SiOpenai,
  opensearch: SiOpensearch,
  parallel: undefined,
  parquet: SiApacheparquet,
  parquet_decode: SiApacheparquet,
  parquet_encode: SiApacheparquet,
  parse_log: FileSearch,
  pg_stream: SiPostgresql,
  pinecone: PineconeLogo,
  postgres_cdc: SiPostgresql,
  processors: Cpu,
  prometheus: SiPrometheus,
  protobuf: GoogleProtocolBuffersLogo,
  pulsar: SiApachepulsar,
  pusher: SiPusher,
  qdrant: QdrantLogo,
  questdb: QuestdbLogo,
  rate_limit: Activity,
  re_match: undefined,
  read_until: undefined,
  redis: SiRedis,
  redis_hash: SiRedis,
  redis_list: SiRedis,
  redis_pubsub: SiRedis,
  redis_scan: SiRedis,
  redis_script: SiRedis,
  redis_streams: SiRedis,
  redpanda: RedpandaLogo,
  redpanda_common: RedpandaLogo,
  redpanda_data_transform: RedpandaLogo,
  redpanda_migrator: RedpandaLogo,
  redpanda_migrator_bundle: RedpandaLogo,
  redpanda_migrator_offsets: RedpandaLogo,
  reject: undefined,
  reject_errored: undefined,
  resource: Package,
  retry: RefreshCw,
  ristretto: SiDgraph,
  schema_registry: ConfluentincLogo,
  schema_registry_decode: ConfluentincLogo,
  schema_registry_encode: ConfluentincLogo,
  select_parts: undefined,
  sentry_capture: SiSentry,
  sequence: undefined,
  sftp: undefined,
  skip_bom: undefined,
  slack: SiSlack,
  slack_post: SiSlack,
  slack_reaction: SiSlack,
  slack_thread: SiSlack,
  slack_users: SiSlack,
  sleep: undefined,
  snowflake_put: SiSnowflake,
  snowflake_streaming: SiSnowflake,
  socket: Network,
  socket_server: Server,
  spicedb_watch: AuthzedLogo,
  split: undefined,
  splunk: SiSplunk,
  splunk_hec: SiSplunk,
  sql: Database,
  sql_driver_clickhouse: SiClickhouse,
  sql_driver_gocosmos: AzurecosmosdbLogo,
  sql_driver_mssql: MicrosoftsqlserverLogo,
  sql_driver_mysql: SiMysql,
  sql_driver_oracle: OracleLogo,
  sql_driver_postgres: SiPostgresql,
  sql_driver_snowflake: SiSnowflake,
  sql_driver_sqlite: SiSqlite,
  sql_driver_trino: SiTrino,
  stdin: FileInput,
  stdout: FileOutput,
  subprocess: Terminal,
  switch: undefined,
  sync_response: undefined,
  tcp: Network,
  tcp_server: Server,
  text: Type,
  try: undefined,
  unarchive: FolderOpen,
  websocket: WebSocketLogo,
  while: undefined,
  workflow: Workflow,
  xml: XmlLogo,
  zmq4: ZeromqLogo,
} as const;

export type ComponentName = keyof typeof componentLogoMap;
