// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts,js_import_style=legacy_commonjs"
// @generated from file redpanda/api/console/v1alpha1/console_service.proto (package redpanda.api.console.v1alpha1, syntax proto3)
/* eslint-disable */

import { ConsoleService } from "./console_service_pb";

/**
 * PublishMessage publishes message.
 *
 * @generated from rpc redpanda.api.console.v1alpha1.ConsoleService.PublishMessage
 */
export const publishMessage = ConsoleService.method.publishMessage;

/**
 * ListSchemaMessageTypes returns the Protobuf message types defined in a registered schema,
 * including nested types, so clients can pick by name instead of by numeric index.
 *
 * @generated from rpc redpanda.api.console.v1alpha1.ConsoleService.ListSchemaMessageTypes
 */
export const listSchemaMessageTypes = ConsoleService.method.listSchemaMessageTypes;

/**
 * GenerateSchemaSample renders a JSON skeleton for any Schema Registry-backed
 * schema (Avro / Protobuf / JSON Schema). Dispatches by schema type server-side.
 *
 * @generated from rpc redpanda.api.console.v1alpha1.ConsoleService.GenerateSchemaSample
 */
export const generateSchemaSample = ConsoleService.method.generateSchemaSample;
