// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts,js_import_style=legacy_commonjs"
// @generated from file redpanda/api/console/v1alpha1/redpanda_news.proto (package redpanda.api.console.v1alpha1, syntax proto3)
/* eslint-disable */

import { RedpandaNewsService } from "./redpanda_news_pb";

/**
 * ListRedpandaNews retrieves the latest news and updates from Redpanda
 *
 * @generated from rpc redpanda.api.console.v1alpha1.RedpandaNewsService.ListRedpandaNews
 */
export const listRedpandaNews = RedpandaNewsService.method.listRedpandaNews;
