// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file redpanda/api/console/v1alpha1/topic.proto (package redpanda.api.console.v1alpha1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_redpanda_api_auth_v1_authorization } from "../../auth/v1/authorization_pb";
import type { ListTopicsRequest as ListTopicsRequest$1 } from "../../dataplane/v1/topic_pb";
import { file_redpanda_api_dataplane_v1_topic } from "../../dataplane/v1/topic_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file redpanda/api/console/v1alpha1/topic.proto.
 */
export const file_redpanda_api_console_v1alpha1_topic: GenFile = /*@__PURE__*/
  fileDesc("CilyZWRwYW5kYS9hcGkvY29uc29sZS92MWFscGhhMS90b3BpYy5wcm90bxIdcmVkcGFuZGEuYXBpLmNvbnNvbGUudjFhbHBoYTEiUgoRTGlzdFRvcGljc1JlcXVlc3QSPQoHcmVxdWVzdBgBIAEoCzIsLnJlZHBhbmRhLmFwaS5kYXRhcGxhbmUudjEuTGlzdFRvcGljc1JlcXVlc3QiiwQKEkxpc3RUb3BpY3NSZXNwb25zZRJHCgZ0b3BpY3MYASADKAsyNy5yZWRwYW5kYS5hcGkuY29uc29sZS52MWFscGhhMS5MaXN0VG9waWNzUmVzcG9uc2UuVG9waWMSFwoPbmV4dF9wYWdlX3Rva2VuGAIgASgJGjAKDFJlcGxpY2FFcnJvchIRCglicm9rZXJfaWQYASABKAUSDQoFZXJyb3IYAiABKAkajwEKDUxvZ0RpclN1bW1hcnkSGAoQdG90YWxfc2l6ZV9ieXRlcxgBIAEoAxJWCg5yZXBsaWNhX2Vycm9ycxgCIAMoCzI+LnJlZHBhbmRhLmFwaS5jb25zb2xlLnYxYWxwaGExLkxpc3RUb3BpY3NSZXNwb25zZS5SZXBsaWNhRXJyb3ISDAoEaGludBgDIAEoCRrOAQoFVG9waWMSDAoEbmFtZRgBIAEoCRIQCghpbnRlcm5hbBgCIAEoCBIXCg9wYXJ0aXRpb25fY291bnQYAyABKAUSGgoScmVwbGljYXRpb25fZmFjdG9yGAQgASgFEhYKDmNsZWFudXBfcG9saWN5GAUgASgJElgKD2xvZ19kaXJfc3VtbWFyeRgGIAEoCzI/LnJlZHBhbmRhLmFwaS5jb25zb2xlLnYxYWxwaGExLkxpc3RUb3BpY3NSZXNwb25zZS5Mb2dEaXJTdW1tYXJ5MosBCgxUb3BpY1NlcnZpY2USewoKTGlzdFRvcGljcxIwLnJlZHBhbmRhLmFwaS5jb25zb2xlLnYxYWxwaGExLkxpc3RUb3BpY3NSZXF1ZXN0GjEucmVkcGFuZGEuYXBpLmNvbnNvbGUudjFhbHBoYTEuTGlzdFRvcGljc1Jlc3BvbnNlIgiKph0ECAEQAWIGcHJvdG8z", [file_redpanda_api_auth_v1_authorization, file_redpanda_api_dataplane_v1_topic]);

/**
 * ListTopicsRequest wraps the dataplane request so paging and filtering stay in sync with the
 * public API.
 *
 * @generated from message redpanda.api.console.v1alpha1.ListTopicsRequest
 */
export type ListTopicsRequest = Message<"redpanda.api.console.v1alpha1.ListTopicsRequest"> & {
  /**
   * @generated from field: redpanda.api.dataplane.v1.ListTopicsRequest request = 1;
   */
  request?: ListTopicsRequest$1;
};

/**
 * Describes the message redpanda.api.console.v1alpha1.ListTopicsRequest.
 * Use `create(ListTopicsRequestSchema)` to create a new message.
 */
export const ListTopicsRequestSchema: GenMessage<ListTopicsRequest> = /*@__PURE__*/
  messageDesc(file_redpanda_api_console_v1alpha1_topic, 0);

/**
 * ListTopicsResponse is Console-specific rather than a wrapper of the dataplane response: it
 * enriches each topic with data the Console topic list renders but the public dataplane API
 * deliberately does not expose (cleanup policy and on-disk size).
 *
 * @generated from message redpanda.api.console.v1alpha1.ListTopicsResponse
 */
export type ListTopicsResponse = Message<"redpanda.api.console.v1alpha1.ListTopicsResponse"> & {
  /**
   * @generated from field: repeated redpanda.api.console.v1alpha1.ListTopicsResponse.Topic topics = 1;
   */
  topics: ListTopicsResponse_Topic[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message redpanda.api.console.v1alpha1.ListTopicsResponse.
 * Use `create(ListTopicsResponseSchema)` to create a new message.
 */
export const ListTopicsResponseSchema: GenMessage<ListTopicsResponse> = /*@__PURE__*/
  messageDesc(file_redpanda_api_console_v1alpha1_topic, 1);

/**
 * ReplicaError describes a log dir query error for a single broker.
 *
 * @generated from message redpanda.api.console.v1alpha1.ListTopicsResponse.ReplicaError
 */
export type ListTopicsResponse_ReplicaError = Message<"redpanda.api.console.v1alpha1.ListTopicsResponse.ReplicaError"> & {
  /**
   * Broker that returned the error.
   *
   * @generated from field: int32 broker_id = 1;
   */
  brokerId: number;

  /**
   * Error message returned by the broker.
   *
   * @generated from field: string error = 2;
   */
  error: string;
};

/**
 * Describes the message redpanda.api.console.v1alpha1.ListTopicsResponse.ReplicaError.
 * Use `create(ListTopicsResponse_ReplicaErrorSchema)` to create a new message.
 */
export const ListTopicsResponse_ReplicaErrorSchema: GenMessage<ListTopicsResponse_ReplicaError> = /*@__PURE__*/
  messageDesc(file_redpanda_api_console_v1alpha1_topic, 1, 0);

/**
 * LogDirSummary describes the aggregated on-disk size of a topic. Gathering it fans out a
 * DescribeLogDirs request to every broker, so it may be partial: brokers that failed are
 * reported in replica_errors and total_size_bytes is then an estimate.
 *
 * @generated from message redpanda.api.console.v1alpha1.ListTopicsResponse.LogDirSummary
 */
export type ListTopicsResponse_LogDirSummary = Message<"redpanda.api.console.v1alpha1.ListTopicsResponse.LogDirSummary"> & {
  /**
   * Total size of the topic in bytes across all replicas.
   *
   * @generated from field: int64 total_size_bytes = 1;
   */
  totalSizeBytes: bigint;

  /**
   * Errors encountered while querying log dirs from individual brokers.
   *
   * @generated from field: repeated redpanda.api.console.v1alpha1.ListTopicsResponse.ReplicaError replica_errors = 2;
   */
  replicaErrors: ListTopicsResponse_ReplicaError[];

  /**
   * Optional human-readable hint explaining a partial or missing result.
   *
   * @generated from field: string hint = 3;
   */
  hint: string;
};

/**
 * Describes the message redpanda.api.console.v1alpha1.ListTopicsResponse.LogDirSummary.
 * Use `create(ListTopicsResponse_LogDirSummarySchema)` to create a new message.
 */
export const ListTopicsResponse_LogDirSummarySchema: GenMessage<ListTopicsResponse_LogDirSummary> = /*@__PURE__*/
  messageDesc(file_redpanda_api_console_v1alpha1_topic, 1, 1);

/**
 * @generated from message redpanda.api.console.v1alpha1.ListTopicsResponse.Topic
 */
export type ListTopicsResponse_Topic = Message<"redpanda.api.console.v1alpha1.ListTopicsResponse.Topic"> & {
  /**
   * Topic name.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Whether the topic is internal.
   *
   * @generated from field: bool internal = 2;
   */
  internal: boolean;

  /**
   * Topic partition count.
   *
   * @generated from field: int32 partition_count = 3;
   */
  partitionCount: number;

  /**
   * Topic replication factor.
   *
   * @generated from field: int32 replication_factor = 4;
   */
  replicationFactor: number;

  /**
   * Topic cleanup policy (e.g. `delete`, `compact`).
   *
   * @generated from field: string cleanup_policy = 5;
   */
  cleanupPolicy: string;

  /**
   * Aggregated log directory size for the topic across all replicas.
   *
   * @generated from field: redpanda.api.console.v1alpha1.ListTopicsResponse.LogDirSummary log_dir_summary = 6;
   */
  logDirSummary?: ListTopicsResponse_LogDirSummary;
};

/**
 * Describes the message redpanda.api.console.v1alpha1.ListTopicsResponse.Topic.
 * Use `create(ListTopicsResponse_TopicSchema)` to create a new message.
 */
export const ListTopicsResponse_TopicSchema: GenMessage<ListTopicsResponse_Topic> = /*@__PURE__*/
  messageDesc(file_redpanda_api_console_v1alpha1_topic, 1, 2);

/**
 * TopicService is the Console-facing topic API. It exists alongside the dataplane TopicService so
 * that Console-only enrichment does not leak into the public dataplane contract.
 *
 * @generated from service redpanda.api.console.v1alpha1.TopicService
 */
export const TopicService: GenService<{
  /**
   * ListTopics lists topics with the metadata the Console topic list renders.
   *
   * @generated from rpc redpanda.api.console.v1alpha1.TopicService.ListTopics
   */
  listTopics: {
    methodKind: "unary";
    input: typeof ListTopicsRequestSchema;
    output: typeof ListTopicsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_redpanda_api_console_v1alpha1_topic, 0);

