// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file redpanda/api/dataplane/v1/common.proto (package redpanda.api.dataplane.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file redpanda/api/dataplane/v1/common.proto.
 */
export const file_redpanda_api_dataplane_v1_common: GenFile = /*@__PURE__*/
  fileDesc("CiZyZWRwYW5kYS9hcGkvZGF0YXBsYW5lL3YxL2NvbW1vbi5wcm90bxIZcmVkcGFuZGEuYXBpLmRhdGFwbGFuZS52MSJ0Cg1Db25maWdTeW5vbnltEgwKBG5hbWUYASABKAkSEgoFdmFsdWUYAiABKAlIAIgBARI3CgZzb3VyY2UYAyABKA4yJy5yZWRwYW5kYS5hcGkuZGF0YXBsYW5lLnYxLkNvbmZpZ1NvdXJjZUIICgZfdmFsdWUqqQIKDENvbmZpZ1NvdXJjZRIdChlDT05GSUdfU09VUkNFX1VOU1BFQ0lGSUVEEAASJgoiQ09ORklHX1NPVVJDRV9EWU5BTUlDX1RPUElDX0NPTkZJRxABEicKI0NPTkZJR19TT1VSQ0VfRFlOQU1JQ19CUk9LRVJfQ09ORklHEAISLworQ09ORklHX1NPVVJDRV9EWU5BTUlDX0RFRkFVTFRfQlJPS0VSX0NPTkZJRxADEiYKIkNPTkZJR19TT1VSQ0VfU1RBVElDX0JST0tFUl9DT05GSUcQBBIgChxDT05GSUdfU09VUkNFX0RFRkFVTFRfQ09ORklHEAUSLgoqQ09ORklHX1NPVVJDRV9EWU5BTUlDX0JST0tFUl9MT0dHRVJfQ09ORklHEAYq+wEKCkNvbmZpZ1R5cGUSGwoXQ09ORklHX1RZUEVfVU5TUEVDSUZJRUQQABIXChNDT05GSUdfVFlQRV9CT09MRUFOEAESFgoSQ09ORklHX1RZUEVfU1RSSU5HEAISEwoPQ09ORklHX1RZUEVfSU5UEAMSFQoRQ09ORklHX1RZUEVfU0hPUlQQBBIUChBDT05GSUdfVFlQRV9MT05HEAUSFgoSQ09ORklHX1RZUEVfRE9VQkxFEAYSFAoQQ09ORklHX1RZUEVfTElTVBAHEhUKEUNPTkZJR19UWVBFX0NMQVNTEAgSGAoUQ09ORklHX1RZUEVfUEFTU1dPUkQQCSrJAQoUQ29uZmlnQWx0ZXJPcGVyYXRpb24SJgoiQ09ORklHX0FMVEVSX09QRVJBVElPTl9VTlNQRUNJRklFRBAAEh4KGkNPTkZJR19BTFRFUl9PUEVSQVRJT05fU0VUEAESIQodQ09ORklHX0FMVEVSX09QRVJBVElPTl9ERUxFVEUQAhIhCh1DT05GSUdfQUxURVJfT1BFUkFUSU9OX0FQUEVORBADEiMKH0NPTkZJR19BTFRFUl9PUEVSQVRJT05fU1VCVFJBQ1QQBEKQAgodY29tLnJlZHBhbmRhLmFwaS5kYXRhcGxhbmUudjFCC0NvbW1vblByb3RvUAFaW2dpdGh1Yi5jb20vcmVkcGFuZGEtZGF0YS9jb25zb2xlL2JhY2tlbmQvcGtnL3Byb3RvZ2VuL3JlZHBhbmRhL2FwaS9kYXRhcGxhbmUvdjE7ZGF0YXBsYW5ldjGiAgNSQUSqAhlSZWRwYW5kYS5BcGkuRGF0YXBsYW5lLlYxygIZUmVkcGFuZGFcQXBpXERhdGFwbGFuZVxWMeICJVJlZHBhbmRhXEFwaVxEYXRhcGxhbmVcVjFcR1BCTWV0YWRhdGHqAhxSZWRwYW5kYTo6QXBpOjpEYXRhcGxhbmU6OlYxYgZwcm90bzM");

/**
 * @generated from message redpanda.api.dataplane.v1.ConfigSynonym
 */
export type ConfigSynonym = Message<"redpanda.api.dataplane.v1.ConfigSynonym"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: optional string value = 2;
   */
  value?: string;

  /**
   * @generated from field: redpanda.api.dataplane.v1.ConfigSource source = 3;
   */
  source: ConfigSource;
};

/**
 * Describes the message redpanda.api.dataplane.v1.ConfigSynonym.
 * Use `create(ConfigSynonymSchema)` to create a new message.
 */
export const ConfigSynonymSchema: GenMessage<ConfigSynonym> = /*@__PURE__*/
  messageDesc(file_redpanda_api_dataplane_v1_common, 0);

/**
 * @generated from enum redpanda.api.dataplane.v1.ConfigSource
 */
export enum ConfigSource {
  /**
   * @generated from enum value: CONFIG_SOURCE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CONFIG_SOURCE_DYNAMIC_TOPIC_CONFIG = 1;
   */
  DYNAMIC_TOPIC_CONFIG = 1,

  /**
   * @generated from enum value: CONFIG_SOURCE_DYNAMIC_BROKER_CONFIG = 2;
   */
  DYNAMIC_BROKER_CONFIG = 2,

  /**
   * @generated from enum value: CONFIG_SOURCE_DYNAMIC_DEFAULT_BROKER_CONFIG = 3;
   */
  DYNAMIC_DEFAULT_BROKER_CONFIG = 3,

  /**
   * @generated from enum value: CONFIG_SOURCE_STATIC_BROKER_CONFIG = 4;
   */
  STATIC_BROKER_CONFIG = 4,

  /**
   * @generated from enum value: CONFIG_SOURCE_DEFAULT_CONFIG = 5;
   */
  DEFAULT_CONFIG = 5,

  /**
   * @generated from enum value: CONFIG_SOURCE_DYNAMIC_BROKER_LOGGER_CONFIG = 6;
   */
  DYNAMIC_BROKER_LOGGER_CONFIG = 6,
}

/**
 * Describes the enum redpanda.api.dataplane.v1.ConfigSource.
 */
export const ConfigSourceSchema: GenEnum<ConfigSource> = /*@__PURE__*/
  enumDesc(file_redpanda_api_dataplane_v1_common, 0);

/**
 * @generated from enum redpanda.api.dataplane.v1.ConfigType
 */
export enum ConfigType {
  /**
   * @generated from enum value: CONFIG_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CONFIG_TYPE_BOOLEAN = 1;
   */
  BOOLEAN = 1,

  /**
   * @generated from enum value: CONFIG_TYPE_STRING = 2;
   */
  STRING = 2,

  /**
   * @generated from enum value: CONFIG_TYPE_INT = 3;
   */
  INT = 3,

  /**
   * @generated from enum value: CONFIG_TYPE_SHORT = 4;
   */
  SHORT = 4,

  /**
   * @generated from enum value: CONFIG_TYPE_LONG = 5;
   */
  LONG = 5,

  /**
   * @generated from enum value: CONFIG_TYPE_DOUBLE = 6;
   */
  DOUBLE = 6,

  /**
   * @generated from enum value: CONFIG_TYPE_LIST = 7;
   */
  LIST = 7,

  /**
   * @generated from enum value: CONFIG_TYPE_CLASS = 8;
   */
  CLASS = 8,

  /**
   * @generated from enum value: CONFIG_TYPE_PASSWORD = 9;
   */
  PASSWORD = 9,
}

/**
 * Describes the enum redpanda.api.dataplane.v1.ConfigType.
 */
export const ConfigTypeSchema: GenEnum<ConfigType> = /*@__PURE__*/
  enumDesc(file_redpanda_api_dataplane_v1_common, 1);

/**
 * @generated from enum redpanda.api.dataplane.v1.ConfigAlterOperation
 */
export enum ConfigAlterOperation {
  /**
   * @generated from enum value: CONFIG_ALTER_OPERATION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CONFIG_ALTER_OPERATION_SET = 1;
   */
  SET = 1,

  /**
   * @generated from enum value: CONFIG_ALTER_OPERATION_DELETE = 2;
   */
  DELETE = 2,

  /**
   * @generated from enum value: CONFIG_ALTER_OPERATION_APPEND = 3;
   */
  APPEND = 3,

  /**
   * @generated from enum value: CONFIG_ALTER_OPERATION_SUBTRACT = 4;
   */
  SUBTRACT = 4,
}

/**
 * Describes the enum redpanda.api.dataplane.v1.ConfigAlterOperation.
 */
export const ConfigAlterOperationSchema: GenEnum<ConfigAlterOperation> = /*@__PURE__*/
  enumDesc(file_redpanda_api_dataplane_v1_common, 2);

