
input:
  kafka_franz:
    seed_brokers: ["${REDPANDA_BROKERS}"]
    topics: ["${TOPIC}"]
    consumer_group: "${TOPIC}-ai-pipeline"
    tls:
      enabled: true
    sasl:
      - username: ${USERNAME}
        password: ${secrets.KAFKA_PASSWORD}
        mechanism: ${SASL_MECHANISM}
pipeline:
  processors:
  - mapping: |
      root.document = content().string()
  - label: embeddings
    branch:
      processors:
      - openai_embeddings:
          api_key: "${secrets.OPENAI_KEY}"
          model: text-embedding-3-small
          text_mapping: "this.document"
          dimensions: 768
      result_map:
        root.embeddings = this
output:
  sql_insert:
    driver: "postgres"
    dsn: "${secrets.POSTGRES_DSN}"
    table: "${TOPIC}"
    init_statement: |
      CREATE EXTENSION IF NOT EXISTS vector;
      CREATE TABLE IF NOT EXISTS ${TOPIC} (key text PRIMARY KEY, document text, embeddings vector(768));
    columns: [key, document, embeddings]
    args_mapping: root = [ @kafka_key.not_empty() | uuid_v4(), this.document, this.embeddings.vector() ]
    max_in_flight: 8
    batching:
      count: 64
      period: "30s"
