---
name: Skip Enterprise CI for non-code changes
on:
  push:
    paths-ignore:
      - "frontend/**"
      - "backend/**"
      - "Taskfile.yaml"
      - "taskfiles/**"
      - '.github/workflows/repository-dispatch.yml'
      - '.github/workflows/backend-lint-test.yml'
      - '.github/workflows/frontend-verify.yml'
      - 'test-images.json'
    branches:
      - '**'
    tags-ignore:
      - '*'
permissions:
  id-token: write
  contents: read
  statuses: write
jobs:
  skip-enterprise-ci:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.RP_AWS_CRED_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.RP_AWS_CRED_ACCOUNT_ID }}:role/${{ vars.RP_AWS_CRED_BASE_ROLE_NAME }}${{ github.event.repository.name }}
      - uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,sdlc/prod/github/actions_bot_token
          parse-json-secrets: true
      - name: Set success enterprise CI status
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.ACTIONS_BOT_TOKEN }}
          script: |
            await github.rest.repos.createCommitStatus({
              owner: 'redpanda-data',
              repo: 'console',
              sha: context.sha,
              state: 'success',
              description: 'Skipped — no backend/frontend changes',
              context: 'Enterprise CI'
            });